/*制单人为 张超 的、收款对应类型 不是 押金 的收款单,看看其中是不是有不属于销售的回款单*/
SELECT DS.DQBM AS 大区编码,DS.XSHDQ  AS 大区名称,H.CDEPTCODE AS 部门编码,D.CDEPNAME AS 部门名称,C.CCUSNAME AS 客户名称,H.DVOUCHDATE AS 单据日期,H.CVOUCHID AS 单据编号,CASE WHEN H.CCOVOUCHID IS NOT NULL THEN H.CCOVOUCHID ELSE '' END AS 发票号,H.CPERSON AS 业务员编码,H.CDIGEST AS 摘要,H.ISOURCE AS 来源,H.COPERATOR AS 录入人,H.CCANCELNO AS 现结线索,H.VT_ID AS 单据模版号 ,H.CNATBANK AS 本单位银行名称 ,H.CDEFINE9 AS 收款对应类型,H.CSSCODE AS 结算方式编码,SS.CSSNAME AS 结算方式名称,
B.BPREPAY AS 预收预付标志,B.IAMT AS 收款金额,B.IRAMT AS 收款余额
FROM AP_CLOSEBILLS AS B
LEFT JOIN AP_CLOSEBILL AS H ON B.IID = H.IID
LEFT JOIN PERSON P ON H.COPERATOR = P.CPERSONNAME
LEFT JOIN SETTLESTYLE AS SS ON H.CSSCODE = SS.CSSCODE
LEFT JOIN DEPARTMENT AS D ON H.CDEPTCODE = D.CDEPCODE
LEFT JOIN CUSTOMER AS C ON B.CCUSVEN = C.CCUSCODE
LEFT JOIN XSHBMDY AS DS ON H.CDEPTCODE = DS.BMBM
WHERE 1=1
AND ISNULL(H.CDEFINE9,'') <> '押金'
-- AND (H.COPERATOR = '张超' AND h.cCancelNo is NULL and H.COPERATOR = '宋现涛' AND h.cCancelNo is NULL and H.COPERATOR = '李洪波' AND h.cCancelNo is NULL or h.cCancelNo is not NULL)
AND (h.cCancelNo is NULL and H.COPERATOR in ('张超','宋现涛','李洪波') or h.cCancelNo is not NULL)
AND LEFT(H.CSSCODE,1) IN (1,2)
AND (h.vt_id = '8052' and h.cvouchtype = 48)-- 20241118 拆分蓝字单据和红字单据
AND LEFT(CONVERT(NVARCHAR,H.DVOUCHDATE,120),10)>= '${开始日期}'
AND LEFT(CONVERT(NVARCHAR,H.DVOUCHDATE,120),10)<= '${结束日期}' ${if(len(custname) == 0,"","and C.CCUSNAME like '%" + custname + "%'")}
AND H.cVouchID <> '0000000744'
union all 
SELECT DS.DQBM AS 大区编码,DS.XSHDQ  AS 大区名称,H.CDEPTCODE AS 部门编码,D.CDEPNAME AS 部门名称,C.CCUSNAME AS 客户名称,H.DVOUCHDATE AS 单据日期,H.CVOUCHID AS 单据编号,CASE WHEN H.CCOVOUCHID IS NOT NULL THEN H.CCOVOUCHID ELSE '' END AS 发票号,H.CPERSON AS 业务员编码,H.CDIGEST AS 摘要,H.ISOURCE AS 来源,H.COPERATOR AS 录入人,H.CCANCELNO AS 现结线索,H.VT_ID AS 单据模版号 ,H.CNATBANK AS 本单位银行名称 ,H.CDEFINE9 AS 收款对应类型,H.CSSCODE AS 结算方式编码,SS.CSSNAME AS 结算方式名称,
B.BPREPAY AS 预收预付标志,-1.0*B.IAMT AS 收款金额,-1.0*B.IRAMT AS 收款余额
FROM AP_CLOSEBILLS AS B
LEFT JOIN AP_CLOSEBILL AS H ON B.IID = H.IID
LEFT JOIN PERSON P ON H.COPERATOR = P.CPERSONNAME
LEFT JOIN SETTLESTYLE AS SS ON H.CSSCODE = SS.CSSCODE
LEFT JOIN DEPARTMENT AS D ON H.CDEPTCODE = D.CDEPCODE
LEFT JOIN CUSTOMER AS C ON B.CCUSVEN = C.CCUSCODE
LEFT JOIN XSHBMDY AS DS ON H.CDEPTCODE = DS.BMBM
WHERE 1=1
AND ISNULL(H.CDEFINE9,'') <> '押金'
-- AND (H.COPERATOR = '张超' AND h.cCancelNo is NULL and H.COPERATOR = '宋现涛' AND h.cCancelNo is NULL and H.COPERATOR = '李洪波' AND h.cCancelNo is NULL or h.cCancelNo is not NULL)
AND (h.cCancelNo is NULL and H.COPERATOR in ('张超','宋现涛','李洪波') or h.cCancelNo is not NULL)
AND LEFT(H.CSSCODE,1) IN (1,2)
AND (h.vt_id = '8055' and h.cvouchtype = 49 )-- 20241118 拆分蓝字单据和红字单据
AND LEFT(CONVERT(NVARCHAR,H.DVOUCHDATE,120),10)>= '${开始日期}'
AND LEFT(CONVERT(NVARCHAR,H.DVOUCHDATE,120),10)<= '${结束日期}' ${if(len(custname) == 0,"","and C.CCUSNAME like '%" + custname + "%'")}
AND H.cVouchID <> '0000000744'
ORDER BY H.DVOUCHDATE