-- 出口业务海运费的应收单上没有收款协议这一项，需要在做代垫运费发票时将销售订单上的收款协议传过来，然后再传到生成的应收单上

SELECT h.VBILLCODE,b.CINVOICE_BID ,b.CINVOICE_HID  ,b.CFIRSTID ,b.csrcid 来源单据主键,b.VFIRSTCODE ,b.VFIRSTTYPE ,b.VSRCCODE ,b.VSRCTYPE 
FROM dm_prepaidinvoice h
LEFT JOIN dm_prepaidinvoice_b b ON h.CINVOICE_HID = b.CINVOICE_HID 
LEFT JOIN SO_SALEORDER ss ON b.csrcid = ss.CSALEORDERID AND b.VSRCTYPE = '30' AND b.VSRCCODE = ss.VBILLCODE AND ss.dr = 0
WHERE h.VBILLCODE = '48162024011200004426'
;

SELECT DISTINCT  b.VFIRSTTYPE ,b.VSRCTYPE 
FROM dm_prepaidinvoice h
LEFT JOIN dm_prepaidinvoice_b b ON h.CINVOICE_HID = b.CINVOICE_HID 
;
--SRC_BILLID						SRC_BILLTYPE	SRC_ITEMID						TOP_BILLID						TOP_BILLTYPE	TOP_ITEMID						TOP_TRADETYPE
--1001B3100000002CFPY1	30						1001B3100000002CFPY1	1001B3100000002D1ZPR	4816					1001B3100000002D1ZPS	~
SELECT b.SRC_BILLID ,b.SRC_BILLTYPE ,b.SRC_ITEMID ,b.TOP_BILLID ,b.TOP_BILLTYPE ,b.TOP_ITEMID ,b.TOP_TRADETYPE ,b.pk_payterm 
FROM ar_recitem b
LEFT JOIN AR_RECBILL h ON b.PK_RECBILL = h.PK_RECBILL 
WHERE h.BILLNO = '2024010027'
;

CREATE TRIGGER update_pk_payterm_02
BEFORE INSERT ON ar_recitem
FOR EACH ROW
DECLARE
  v_cpaytermid ar_recitem.pk_payterm%TYPE;
BEGIN
  IF :NEW.SRC_BILLTYPE = '30' AND :NEW.TOP_BILLTYPE = '4816' AND :NEW.pk_payterm = '~' THEN
    SELECT cpaytermid INTO v_cpaytermid
    FROM (SELECT cpaytermid,ROW_NUMBER () OVER (PARTITION BY CSALEORDERID ORDER BY CSALEORDERID DESC ) rn FROM SO_SALEORDER WHERE CSALEORDERID = :new.SRC_BILLID AND dr = 0 )
    where rn = 1;
    IF v_cpaytermid IS NOT NULL THEN
      :NEW.pk_payterm := v_cpaytermid;
    END IF;
  END IF;
END;
/
