
CREATE PROCEDURE [dbo].[USP_FR_SALE_FEE_JIANBAN]
@IYEAR INT=2021,
@IPERIOD INT=7
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @NSTEP INT--中间表行数计数
	DECLARE @I  INT--循环月份数
	BEGIN--********临时表定义开始********
		/*维度表*/
		CREATE TABLE #DIM
			(
				IYEAR INT,IPERIOD INT,DIM_DEPT VARCHAR(200) ,DIM_DEPTNAME VARCHAR(200) ,DIM_CUST VARCHAR(100) ,DIM_CUSTNAME VARCHAR(100)
			)
		/*月度费用取数结果临时表，字段包括 凭证分录主键、年度、月份、凭证部门编码、凭证部门名称、凭证客户编码、凭证客户名称、客户部门编码、客户部门名称、部门维度编码、部门维度名称、客户维度、客户维度名称、费用，*/
		CREATE TABLE #FR_FEEDETAIL_0
			(
				IFLAG INT,I_ID INT,IYEAR INT ,IPERIOD INT ,PZDEPT VARCHAR(200) ,PZDEPNAME VARCHAR(200) ,PZCUST VARCHAR(100),PZCUSTNAME VARCHAR(100),CUSTDEPT VARCHAR(100),CUSTDEPTNAME VARCHAR(100),DIM_DEPT VARCHAR(200) ,DIM_DEPTNAME VARCHAR(200) ,DIM_CUST VARCHAR(100),DIM_CUSTNAME VARCHAR(100) ,FEE DECIMAL(20,2)
			)
		/*能够同时匹配部门和客户的数据，数据是汇总数据*/
		CREATE TABLE #FR_FEEDETAIL_DC
			(
				IYEAR INT ,IPERIOD INT ,DIM_DEPT VARCHAR(100),DIM_DEPTNAME VARCHAR(100),DIM_CUST VARCHAR(100),DIM_CUSTNAME VARCHAR(100),FEE_DC DECIMAL(20,2)
			)
		/*能匹配部门不能匹配客户的数据*/
		CREATE TABLE #FR_FEEDETAIL_D
			(
				IYEAR INT ,IPERIOD INT ,DIM_DEPT VARCHAR(100),DIM_DEPTNAME VARCHAR(100),FEE_D DECIMAL(20,2)
			)
		/*能匹配客户不能匹配部门的数据*/
		CREATE TABLE #FR_FEEDETAIL_C
			(
				IYEAR INT ,IPERIOD INT ,DIM_CUST VARCHAR(100),DIM_CUSTNAME VARCHAR(100),FEE_C DECIMAL(20,2)
			)
		/*部门和客户都不能匹配的数据*/
		CREATE TABLE #FR_FEEDETAIL_Z
			(
				IYEAR INT ,IPERIOD INT ,FEE_Z DECIMAL(20,2)
			)
		/*收入取数明细表，字段包括 发票行主键、年度、月份、单据部门编码、单据部门名称、单据客户编码、单据客户名称、客户关联部门编码、客户关联部门名称、部门维度编码、部门维度名称、客户维度编码、客户维度名称、发票金额
		*/
		CREATE TABLE #FR_SALE_DETAILS
			(
				IFLAG INT,AutoID VARCHAR(100),IYEAR INT ,IPERIOD INT ,FPDEPT VARCHAR(100),FPDEPTNAME VARCHAR(100),FPCUST VARCHAR(100),FPCUSTNAME VARCHAR(100),CUSTDEPT VARCHAR(100),CUSTDEPTNAME VARCHAR(100),DIM_DEPT VARCHAR(100),DIM_DEPTNAME VARCHAR(100) ,DIM_CUST VARCHAR(100),DIM_CUSTNAME VARCHAR(100) , NMNY DECIMAL(20,2)
			)
		/*能够同时匹配部门和客户的数据，数据是汇总数据*/
		CREATE TABLE #FR_SALE_DETAIL_DC
			(
				IYEAR INT ,IPERIOD INT ,DIM_DEPT VARCHAR(100),DIM_DEPTNAME VARCHAR(100),DIM_CUST VARCHAR(100),DIM_CUSTNAME VARCHAR(100),NMNY_DC_M DECIMAL(20,2),NMNY_DC_Y DECIMAL(20,2)
			)
		/*能匹配部门不能匹配客户的数据*/
		CREATE TABLE #FR_SALE_DETAIL_D
			(
				IYEAR INT ,IPERIOD INT ,DIM_DEPT VARCHAR(100),DIM_DEPTNAME VARCHAR(100),NMNY_D_M DECIMAL(20,2),NMNY_D_Y DECIMAL(20,2)
			)
		/*能匹配客户不能匹配部门的数据*/
		CREATE TABLE #FR_SALE_DETAIL_C
			(
				IYEAR INT ,IPERIOD INT ,DIM_CUST VARCHAR(100),DIM_CUSTNAME VARCHAR(100),NMNY_C_M DECIMAL(20,2),NMNY_C_Y DECIMAL(20,2)
			)
		/*部门和客户都不能匹配的数据*/
		CREATE TABLE #FR_SALE_DETAIL_Z
			(
				IYEAR INT ,IPERIOD INT ,NMNY_Z_M DECIMAL(20,2),NMNY_Z_Y DECIMAL(20,2)
			)
		/*月度数据结果按维度分类存放临时表，字段包括 年度、月份、部门维度、客户维度、客户费用、部门费用、公共费用，月度客户收入、月度部门收入、月度总收入，年度客户收入、年度部门收入、年度总收入**/
		CREATE TABLE #FR_FEEDETAIL_1
			(
				IYEAR INT ,IPERIOD INT ,DIM_DEPT VARCHAR(200) ,DIM_DEPTNAME VARCHAR(200),DIM_CUST VARCHAR(100) ,DIM_CUSTNAME VARCHAR(100) ,FEE_DC DECIMAL(20,2),FEE_D DECIMAL(20,2),FEE_C DECIMAL(20,2),FEE_Z DECIMAL(20,2),NMNY_DC_M DECIMAL(20,2),NMNY_D_M DECIMAL(20,2),NMNY_C_M DECIMAL(20,2),NMNY_Z_M DECIMAL(20,2),NMNY_DC_Y DECIMAL(20,2),NMNY_D_Y DECIMAL(20,2),NMNY_C_Y DECIMAL(20,2),NMNY_Z_Y DECIMAL(20,2),NCUSTCOUNT INT,FEE_D_FT DECIMAL(20,2) ,FEE_C_FT DECIMAL(20,2) ,FEE_Z_FT DECIMAL(20,2)
			)
	END--********临时表定义结束********

	BEGIN/*组建维度表开始*/
		IF(@IPERIOD = 12)
			BEGIN
				INSERT INTO #DIM
				SELECT DISTINCT T.IYEAR, T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME
				FROM (
					SELECT DISTINCT
						@IYEAR AS IYEAR,@IPERIOD AS IPERIOD,ISNULL(CUST.CCUSDEPART,'未匹配') AS DIM_DEPT,D.CDEPNAME AS DIM_DEPTNAME,ISNULL(H.CCUSCODE,'未匹配') AS DIM_CUST,CASE WHEN H.CCUSCODE IS NOT NULL THEN CUST.CCUSNAME ELSE '未匹配'END AS DIM_CUSTNAME
						FROM SALEBILLVOUCHS B
						LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
						LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
						LEFT JOIN DEPARTMENT D ON CUST.CCUSDEPART = D.CDEPCODE
						WHERE ((YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = 12) OR (YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = 12))  AND CUST.CCUSDEPART IS NOT NULL AND CUST.CCUSCODE <> '010124004'/*市场部（古）*/ AND  CUST.CCUSCODE <> '040000717'/*四川圆明园*/
						UNION
					SELECT DISTINCT
					 	@IYEAR-1 AS IYEAR,@IPERIOD AS IPERIOD,ISNULL(CUST.CCUSDEPART,'未匹配') AS DIM_DEPT,D.CDEPNAME AS DIM_DEPTNAME,ISNULL(H.CCUSCODE,'未匹配') AS DIM_CUST,CASE WHEN H.CCUSCODE IS NOT NULL THEN CUST.CCUSNAME ELSE '未匹配'END AS DIM_CUSTNAME
						FROM SALEBILLVOUCHS B
						LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
						LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
						LEFT JOIN DEPARTMENT D ON CUST.CCUSDEPART = D.CDEPCODE
						WHERE ((YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = 12) OR (YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = 12))  AND CUST.CCUSDEPART IS NOT NULL AND CUST.CCUSCODE <> '010124004'/*市场部（古）*/ AND  CUST.CCUSCODE <> '040000717'/*四川圆明园*/
					UNION
					SELECT DISTINCT @IYEAR AS IYEAR,@IPERIOD AS IPERIOD,ISNULL(CUST.CCUSDEPART,'未匹配') AS DIM_DEPT,D2.CDEPNAME AS DIM_DEPTNAME,
						CASE WHEN CUST.CCUSDEPART IS NOT NULL THEN CUST.CCUSCODE ELSE '未匹配' END AS DIM_CUST,CASE WHEN CUST.CCUSDEPART IS NOT NULL THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME
						FROM GL_ACCVOUCH T
						LEFT JOIN CODE C ON  T.CCODE = C.CCODE AND T.IYEAR = C.IYEAR
						LEFT JOIN CUSTOMER CUST ON T.CCUS_ID = CUST.CCUSCODE
						LEFT JOIN DEPARTMENT D1 ON T.CDEPT_ID = D1.CDEPCODE
						LEFT JOIN DEPARTMENT D2 ON CUST.CCUSDEPART = D2.CDEPCODE
						WHERE LEFT(C.CCODE,4) = 5501
							AND T.CDIGEST <> '期间损益结转'
							AND ((T.IYEAR = @IYEAR AND T.IPERIOD = 12 ) OR (T.IYEAR = @IYEAR-1 AND T.IPERIOD = 12 ))
							AND CUST.CCUSCODE <> '010124004'/*市场部（古）*/ AND  CUST.CCUSCODE <> '040000717'/*四川圆明园*/
					UNION
					SELECT DISTINCT @IYEAR-1 AS IYEAR,@IPERIOD AS IPERIOD,ISNULL(CUST.CCUSDEPART,'未匹配') AS DIM_DEPT,D2.CDEPNAME AS DIM_DEPTNAME,
						CASE WHEN CUST.CCUSDEPART IS NOT NULL THEN CUST.CCUSCODE ELSE '未匹配' END AS DIM_CUST,CASE WHEN CUST.CCUSDEPART IS NOT NULL THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME
						FROM GL_ACCVOUCH T
						LEFT JOIN CODE C ON  T.CCODE = C.CCODE AND T.IYEAR = C.IYEAR
						LEFT JOIN CUSTOMER CUST ON T.CCUS_ID = CUST.CCUSCODE
						LEFT JOIN DEPARTMENT D1 ON T.CDEPT_ID = D1.CDEPCODE
						LEFT JOIN DEPARTMENT D2 ON CUST.CCUSDEPART = D2.CDEPCODE
						WHERE LEFT(C.CCODE,4) = 5501
							AND T.CDIGEST <> '期间损益结转'
							AND ((T.IYEAR = @IYEAR AND T.IPERIOD = 12 ) OR (T.IYEAR = @IYEAR-1 AND T.IPERIOD = 12 ))
							AND CUST.CCUSCODE <> '010124004'/*市场部（古）*/ AND  CUST.CCUSCODE <> '040000717'/*四川圆明园*/
				) T
			END
		IF(@IPERIOD <> 12)
			BEGIN
				SET @NSTEP = 0
				WHILE(@NSTEP <= @IPERIOD)
				BEGIN
					INSERT INTO #DIM
					SELECT DISTINCT T.IYEAR, T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME
					FROM (
						SELECT DISTINCT @IYEAR AS IYEAR,@NSTEP AS IPERIOD,ISNULL(CUST.CCUSDEPART,'未匹配') AS DIM_DEPT,D.CDEPNAME AS DIM_DEPTNAME,ISNULL(H.CCUSCODE,'未匹配') AS DIM_CUST,CASE WHEN H.CCUSCODE IS NOT NULL THEN CUST.CCUSNAME ELSE '未匹配'END AS DIM_CUSTNAME
						FROM SALEBILLVOUCHS B
						LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
						LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
						LEFT JOIN DEPARTMENT D ON CUST.CCUSDEPART = D.CDEPCODE
						WHERE (((YEAR(H.DDATE) = @IYEAR OR YEAR(H.DDATE) = @IYEAR-1) AND MONTH(H.DDATE) <= @IPERIOD) OR ((YEAR(H.DDATE) = @IYEAR-1 OR YEAR(H.DDATE) = @IYEAR-2) AND MONTH(H.DDATE) >= 11)) AND CUST.CCUSDEPART IS NOT NULL AND CUST.CCUSCODE <> '010124004'/*市场部（古）*/ AND  CUST.CCUSCODE <> '040000717'/*四川圆明园*/
						UNION
						SELECT DISTINCT @IYEAR-1 AS IYEAR,@NSTEP AS IPERIOD,ISNULL(CUST.CCUSDEPART,'未匹配') AS DIM_DEPT,D.CDEPNAME AS DIM_DEPTNAME,ISNULL(H.CCUSCODE,'未匹配') AS DIM_CUST,CASE WHEN H.CCUSCODE IS NOT NULL THEN CUST.CCUSNAME ELSE '未匹配'END AS DIM_CUSTNAME
						FROM SALEBILLVOUCHS B
						LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
						LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
						LEFT JOIN DEPARTMENT D ON CUST.CCUSDEPART = D.CDEPCODE
						WHERE (((YEAR(H.DDATE) = @IYEAR OR YEAR(H.DDATE) = @IYEAR-1) AND MONTH(H.DDATE) <= @IPERIOD) OR ((YEAR(H.DDATE) = @IYEAR-1 OR YEAR(H.DDATE) = @IYEAR-2) AND MONTH(H.DDATE) >= 11))  AND CUST.CCUSDEPART IS NOT NULL AND CUST.CCUSCODE <> '010124004'/*市场部（古）*/ AND  CUST.CCUSCODE <> '040000717'/*四川圆明园*/
						UNION
						SELECT DISTINCT @IYEAR AS IYEAR,@NSTEP AS IPERIOD,ISNULL(CUST.CCUSDEPART,'未匹配') AS DIM_DEPT,D2.CDEPNAME AS DIM_DEPTNAME,
						CASE WHEN CUST.CCUSDEPART IS NOT NULL THEN CUST.CCUSCODE ELSE '未匹配' END AS DIM_CUST,CASE WHEN CUST.CCUSDEPART IS NOT NULL THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME
						FROM GL_ACCVOUCH T
						LEFT JOIN CODE C ON  T.CCODE = C.CCODE AND T.IYEAR = C.IYEAR
						LEFT JOIN CUSTOMER CUST ON T.CCUS_ID = CUST.CCUSCODE
						LEFT JOIN DEPARTMENT D1 ON T.CDEPT_ID = D1.CDEPCODE
						LEFT JOIN DEPARTMENT D2 ON CUST.CCUSDEPART = D2.CDEPCODE
						WHERE LEFT(C.CCODE,4) = 5501
						AND T.CDIGEST <> '期间损益结转'
						AND (((T.IYEAR = @IYEAR OR T.IYEAR = @IYEAR-1) AND T.IPERIOD <= @NSTEP ) OR ((T.IYEAR = @IYEAR-1 OR T.IYEAR = @IYEAR-2) AND T.IPERIOD = 12 ))
						 AND CUST.CCUSDEPART IS NOT NULL AND CUST.CCUSCODE <> '010124004'/*市场部（古）*/ AND  CUST.CCUSCODE <> '040000717'/*四川圆明园*/
						UNION ALL
						SELECT DISTINCT @IYEAR-1 AS IYEAR,@NSTEP AS IPERIOD,ISNULL(CUST.CCUSDEPART,'未匹配') AS DIM_DEPT,D2.CDEPNAME AS DIM_DEPTNAME,
						CASE WHEN CUST.CCUSDEPART IS NOT NULL THEN CUST.CCUSCODE ELSE '未匹配' END AS DIM_CUST,CASE WHEN CUST.CCUSDEPART IS NOT NULL THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME
						FROM GL_ACCVOUCH T
						LEFT JOIN CODE C ON  T.CCODE = C.CCODE AND T.IYEAR = C.IYEAR
						LEFT JOIN CUSTOMER CUST ON T.CCUS_ID = CUST.CCUSCODE
						LEFT JOIN DEPARTMENT D1 ON T.CDEPT_ID = D1.CDEPCODE
						LEFT JOIN DEPARTMENT D2 ON CUST.CCUSDEPART = D2.CDEPCODE
						WHERE LEFT(C.CCODE,4) = 5501
						AND T.CDIGEST <> '期间损益结转'
						AND (((T.IYEAR = @IYEAR OR T.IYEAR = @IYEAR-1) AND T.IPERIOD <= @NSTEP ) OR ((T.IYEAR = @IYEAR-1 OR T.IYEAR = @IYEAR-2) AND T.IPERIOD = 12 )) AND CUST.CCUSDEPART IS NOT NULL AND CUST.CCUSCODE <> '010124004'/*市场部（古）*/ AND  CUST.CCUSCODE <> '040000717'/*四川圆明园*/
					) T
					SET @NSTEP = @NSTEP + 1
				END
			END
	END/*组建维度表结束*/

	BEGIN/*取费用明细数据开始*/
		/*计算月度费用取数结果，存入临时表，字段包括 年度、月份、凭证部门、凭证客户、客户档案上的部门、部门维度、客户维度、费用*/
		INSERT INTO #FR_FEEDETAIL_0
			SELECT 0 as IFLAG,A.I_ID,A.IYEAR,A.IPERIOD,A.PZDEPT,A.PZDEPTNAME,A.PZCUST,A.PZCUSTNAME,A.CUSTDEPT,A.CUSTDEPTNAME,A.DIM_DEPT,A.DIM_DEPTNAME,A.DIM_CUST,A.DIM_CUSTNAME,A.FEE
			FROM
				(SELECT T.I_ID, @IYEAR AS IYEAR,CASE WHEN T.IPERIOD = 12 THEN 0 ELSE T.IPERIOD END IPERIOD,
					T.CDEPT_ID AS PZDEPT,D1.CDEPNAME AS PZDEPTNAME,T.CCUS_ID AS PZCUST,CUST.CCUSNAME AS PZCUSTNAME,CUST.CCUSDEPART AS CUSTDEPT,D2.CDEPNAME AS CUSTDEPTNAME,
					CASE WHEN  CUST.CCUSDEPART IN (SELECT DISTINCT DIM_DEPT FROM #DIM) THEN CUST.CCUSDEPART
						WHEN (CUST.CCUSDEPART NOT IN (SELECT DISTINCT DIM_DEPT FROM #DIM) OR CUST.CCUSDEPART IS NULL) AND  T.CDEPT_ID IN (SELECT DISTINCT DIM_DEPT FROM #DIM) THEN T.CDEPT_ID
						ELSE '未匹配' END DIM_DEPT,
					CASE WHEN  CUST.CCUSDEPART IN (SELECT DISTINCT DIM_DEPT FROM #DIM) THEN D2.CDEPNAME
						WHEN (CUST.CCUSDEPART NOT IN (SELECT DISTINCT DIM_DEPT FROM #DIM) OR CUST.CCUSDEPART IS NULL) AND  T.CDEPT_ID IN (SELECT DISTINCT DIM_DEPT FROM #DIM) THEN D1.CDEPNAME
						ELSE '未匹配' END DIM_DEPTNAME,
					CASE WHEN CUST.CCUSCODE IN (SELECT DISTINCT DIM_CUST FROM #DIM) THEN CUST.CCUSCODE ELSE '未匹配' END DIM_CUST,
					CASE WHEN CUST.CCUSCODE IN (SELECT DISTINCT DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END DIM_CUSTNAME,
					(T.MD - T.MC) AS FEE
					FROM GL_ACCVOUCH T
					LEFT JOIN CODE C ON  T.CCODE = C.CCODE AND T.IYEAR = C.IYEAR
					LEFT JOIN CUSTOMER CUST ON T.CCUS_ID = CUST.CCUSCODE
					LEFT JOIN DEPARTMENT D1 ON T.CDEPT_ID = D1.CDEPCODE
					LEFT JOIN DEPARTMENT D2 ON CUST.CCUSDEPART = D2.CDEPCODE
					WHERE LEFT(C.CCODE,4) = 5501
						AND T.CDIGEST <> '期间损益结转'
						AND ((T.IYEAR = @IYEAR AND T.IPERIOD <= @IPERIOD AND T.IPERIOD>0) OR (T.IYEAR = @IYEAR-1 AND T.IPERIOD = 12 ))
				UNION ALL
				SELECT  T.I_ID,@IYEAR-1 AS IYEAR,CASE WHEN T.IPERIOD = 12 THEN 0 ELSE T.IPERIOD END IPERIOD,
					T.CDEPT_ID AS PZDEPT,D1.CDEPNAME AS PZDEPTNAME,T.CCUS_ID AS PZCUST,CUST.CCUSNAME AS PZCUSTNAME,CUST.CCUSDEPART AS CUSTDEPT,D2.CDEPNAME AS CUSTDEPTNAME,
					CASE WHEN  CUST.CCUSDEPART IN (SELECT DISTINCT DIM_DEPT FROM #DIM) THEN CUST.CCUSDEPART
						WHEN (CUST.CCUSDEPART NOT IN (SELECT DISTINCT DIM_DEPT FROM #DIM) OR CUST.CCUSDEPART IS NULL) AND  T.CDEPT_ID IN (SELECT DISTINCT DIM_DEPT FROM #DIM) THEN T.CDEPT_ID
						ELSE '未匹配' END DIM_DEPT,
					CASE WHEN  CUST.CCUSDEPART IN (SELECT DISTINCT DIM_DEPT FROM #DIM) THEN D2.CDEPNAME
						WHEN (CUST.CCUSDEPART NOT IN (SELECT DISTINCT DIM_DEPT FROM #DIM) OR CUST.CCUSDEPART IS NULL) AND  T.CDEPT_ID IN (SELECT DISTINCT DIM_DEPT FROM #DIM) THEN D1.CDEPNAME
						ELSE '未匹配' END DIM_DEPTNAME,
					CASE WHEN CUST.CCUSCODE IN (SELECT DISTINCT DIM_CUST FROM #DIM) THEN CUST.CCUSCODE ELSE '未匹配' END DIM_CUST,
					CASE WHEN CUST.CCUSCODE IN (SELECT DISTINCT DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END DIM_CUSTNAME,
					(T.MD - T.MC) AS FEE
					FROM GL_ACCVOUCH T
					LEFT JOIN CODE C ON  T.CCODE = C.CCODE AND T.IYEAR = C.IYEAR
					LEFT JOIN CUSTOMER CUST ON T.CCUS_ID = CUST.CCUSCODE
					LEFT JOIN DEPARTMENT D1 ON T.CDEPT_ID = D1.CDEPCODE
					LEFT JOIN DEPARTMENT D2 ON CUST.CCUSDEPART = D2.CDEPCODE
					WHERE LEFT(C.CCODE,4) = 5501
						AND T.CDIGEST <> '期间损益结转'
						AND ((T.IYEAR = @IYEAR-1 AND T.IPERIOD <= @IPERIOD AND T.IPERIOD > 0 ) OR (T.IYEAR = @IYEAR-2 AND T.IPERIOD = 12 ))
			) A
	END/*取费用明细数据结束*/

	BEGIN/*取折让返利数据，写入费用明细数据开始*/
		IF(@IPERIOD = 12)
			BEGIN
				INSERT INTO #FR_FEEDETAIL_0
				SELECT 1 as IFLAG,T.AutoID AS I_ID,T.IYEAR ASIYEAR ,T.IPERIOD AS IPERIOD,T.FPDEPT AS PZDEPT,T.FPDEPTNAME AS PZDEPTNAME,T.FPCUST AS PZCUST,T.FPCUSTNAME AS PZCUSTNAME,T.CUSTDEPT AS CUSTDEPT,T.CUSTDEPTNAME AS CUSTDEPTNAME,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,-0.5*NTAXMNY AS FEE/*20220819,费用按已经全部记录费用科目，此处折半费用减除*/
				FROM (
					SELECT B.AutoID AS AutoID ,@IYEAR AS IYEAR,@IPERIOD AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
						CASE
							/*十二月收入，11月26日到12月31日*/
							WHEN YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) = 12   THEN B.INATSUM
							WHEN YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 THEN B.INATSUM
							ELSE 0 END AS NTAXMNY

					FROM SALEBILLVOUCHS B
					LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
					LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
					LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
					LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
					WHERE  B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) >= 11
						AND H.cSTCode IN('02','03') AND b.iTaxUnitPrice >= 78
					UNION ALL
					SELECT B.AutoID AS AutoID ,@IYEAR-1 AS IYEAR,@IPERIOD AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
						CASE
							/*十二月收入，11月26日到12月31日*/
							WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 12   THEN B.INATSUM
							WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 THEN B.INATSUM
							ELSE 0 END AS NTAXMNY
					FROM SALEBILLVOUCHS B
					LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
					LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
					LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
					LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
					WHERE   B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE)>= 11
						AND H.cSTCode IN('02','03') AND b.iTaxUnitPrice >= 78
				)T
			END
		IF(@IPERIOD <> 12)
			BEGIN
				SET @I = 0
				WHILE(@I <= @IPERIOD)
					BEGIN
						INSERT INTO #FR_FEEDETAIL_0
						SELECT 1 as IFLAG,T.AutoID AS I_ID,T.IYEAR ASIYEAR ,T.IPERIOD AS IPERIOD,T.FPDEPT AS PZDEPT,T.FPDEPTNAME AS PZDEPTNAME,T.FPCUST AS PZCUST,T.FPCUSTNAME AS PZCUSTNAME,T.CUSTDEPT AS CUSTDEPT,T.CUSTDEPTNAME AS CUSTDEPTNAME,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,-0.5*NTAXMNY AS FEE/*20220819,费用按已经全部记录费用科目，此处折半费用减除*/
						FROM (
							SELECT B.AutoID AS AutoID ,@IYEAR AS IYEAR,@I AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,
								D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
								CASE
									/*十二月收入，11月26日到12月31日*/
									WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 12  AND @I = 0 THEN B.INATSUM
									WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 AND @I = 0 THEN B.INATSUM
									/*一月收入，1月1日到1月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = 1 AND DAY(H.DDATE) <= 25 AND @I = 1 THEN B.INATSUM
									/*二月到十一月收入，上月26日到本月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = @I - 1 AND DAY(H.DDATE) > 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = @I AND DAY(H.DDATE) <= 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									ELSE 0 END AS NTAXMNY
							FROM SALEBILLVOUCHS B
							LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
							LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
							LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
							LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
							WHERE  B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND ((YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) <= @I ) OR (YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) >= 11 ))
								AND H.cSTCode IN('02','03') AND b.iTaxUnitPrice >= 78
							UNION ALL
							SELECT B.AutoID AS AutoID ,@IYEAR-1 AS IYEAR,@I AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
								CASE
									/*十二月收入，11月26日到12月31日*/
									WHEN YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) = 12  AND @I = 0 THEN B.INATSUM
									WHEN YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 AND @I = 0 THEN B.INATSUM
									/*一月收入，1月1日到1月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = 1 AND DAY(H.DDATE) <= 25 AND @I = 1 THEN B.INATSUM
									/*二月到十一月收入，上月26日到本月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = @I - 1 AND DAY(H.DDATE) > 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = @I AND DAY(H.DDATE) <= 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									ELSE 0 END AS NTAXMNY
							FROM SALEBILLVOUCHS B
							LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
							LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
							LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
							LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
							WHERE   B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND ((YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) <= @I ) OR (YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) >= 11 ))
								AND H.cSTCode IN('02','03') AND b.iTaxUnitPrice >= 78
						)T
					SET @I = @I + 1
					END
			END
	END/*取折让返利数据，写入费用明细数据结束*/

	BEGIN/*取收入明细数据开始*/
		IF(@IPERIOD = 12)
			BEGIN
				INSERT INTO #FR_SALE_DETAILS
				SELECT 0 as IFLAG,T.AutoID,T.IYEAR,T.IPERIOD AS IPERIOD,T.FPDEPT,T.FPDEPTNAME,T.FPCUST,T.FPCUSTNAME,T.CUSTDEPT,T.CUSTDEPTNAME,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,NTAXMNY AS NMNY
				FROM (
					SELECT B.AutoID AS AutoID ,@IYEAR AS IYEAR,@IPERIOD AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
						CASE
							/*十二月收入，11月26日到12月31日*/
							WHEN YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) = 12   THEN B.INATSUM
							WHEN YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 THEN B.INATSUM
							ELSE 0 END AS NTAXMNY

					FROM SALEBILLVOUCHS B
					LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
					LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
					LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
					LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
					WHERE  B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) >= 11
					UNION ALL
					SELECT B.AutoID AS AutoID ,@IYEAR-1 AS IYEAR,@IPERIOD AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
						CASE
							/*十二月收入，11月26日到12月31日*/
							WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 12   THEN B.INATSUM
							WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 THEN B.INATSUM
							ELSE 0 END AS NTAXMNY
					FROM SALEBILLVOUCHS B
					LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
					LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
					LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
					LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
					WHERE   B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE)>= 11
				)T
			END
		IF(@IPERIOD <> 12)
			BEGIN
				SET @I = 0
				WHILE(@I <= @IPERIOD)
					BEGIN
						INSERT INTO #FR_SALE_DETAILS
						SELECT 0 as IFLAG,T.AutoID,T.IYEAR,T.IPERIOD AS IPERIOD,T.FPDEPT,T.FPDEPTNAME,T.FPCUST,T.FPCUSTNAME,T.CUSTDEPT,T.CUSTDEPTNAME,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,NTAXMNY AS NMNY
						FROM (
							SELECT B.AutoID AS AutoID ,@IYEAR AS IYEAR,@I AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,
								D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
								CASE
									/*十二月收入，11月26日到12月31日*/
									WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 12  AND @I = 0 THEN B.INATSUM
									WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 AND @I = 0 THEN B.INATSUM
									/*一月收入，1月1日到1月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = 1 AND DAY(H.DDATE) <= 25 AND @I = 1 THEN B.INATSUM
									/*二月到十一月收入，上月26日到本月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = @I - 1 AND DAY(H.DDATE) > 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = @I AND DAY(H.DDATE) <= 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									ELSE 0 END AS NTAXMNY
							FROM SALEBILLVOUCHS B
							LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
							LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
							LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
							LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
							WHERE  B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND ((YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) <= @I ) OR (YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) >= 11 ))
							UNION ALL
							SELECT B.AutoID AS AutoID ,@IYEAR-1 AS IYEAR,@I AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
								CASE
									/*十二月收入，11月26日到12月31日*/
									WHEN YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) = 12  AND @I = 0 THEN B.INATSUM
									WHEN YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 AND @I = 0 THEN B.INATSUM
									/*一月收入，1月1日到1月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = 1 AND DAY(H.DDATE) <= 25 AND @I = 1 THEN B.INATSUM
									/*二月到十一月收入，上月26日到本月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = @I - 1 AND DAY(H.DDATE) > 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = @I AND DAY(H.DDATE) <= 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									ELSE 0 END AS NTAXMNY
							FROM SALEBILLVOUCHS B
							LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
							LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
							LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
							LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
							WHERE   B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND ((YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) <= @I ) OR (YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) >= 11 ))
						)T
					SET @I = @I + 1
					END
			END
	END/*取收入明细数据结束*/

	BEGIN/*计算折让、返利的收入明细数据开始*/
		IF(@IPERIOD = 12)
			BEGIN
				INSERT INTO #FR_SALE_DETAILS
				SELECT 1 as IFLAG,T.AutoID,T.IYEAR,T.IPERIOD AS IPERIOD,T.FPDEPT,T.FPDEPTNAME,T.FPCUST,T.FPCUSTNAME,T.CUSTDEPT,T.CUSTDEPTNAME,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,-0.5*NTAXMNY AS NMNY
				FROM (
					SELECT B.AutoID AS AutoID ,@IYEAR AS IYEAR,@IPERIOD AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
						CASE
							/*十二月收入，11月26日到12月31日*/
							WHEN YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) = 12   THEN B.INATSUM
							WHEN YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 THEN B.INATSUM
							ELSE 0 END AS NTAXMNY

					FROM SALEBILLVOUCHS B
					LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
					LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
					LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
					LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
					WHERE  B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND YEAR(H.DDATE) = @IYEAR AND  MONTH(H.DDATE) >= 11
						AND H.cSTCode IN('02','03') AND b.iTaxUnitPrice >= 78
					UNION ALL
					SELECT B.AutoID AS AutoID ,@IYEAR-1 AS IYEAR,@IPERIOD AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
						CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
						CASE
							/*十二月收入，11月26日到12月31日*/
							WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 12   THEN B.INATSUM
							WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 THEN B.INATSUM
							ELSE 0 END AS NTAXMNY
					FROM SALEBILLVOUCHS B
					LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
					LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
					LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
					LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
					WHERE   B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE)>= 11
						AND H.cSTCode IN('02','03') AND b.iTaxUnitPrice >= 78
				)T
			END
		IF(@IPERIOD <> 12)
			BEGIN
				SET @I = 0
				WHILE(@I <= @IPERIOD)
					BEGIN
						INSERT INTO #FR_SALE_DETAILS
						SELECT 1 as IFLAG,T.AutoID,T.IYEAR,T.IPERIOD AS IPERIOD,T.FPDEPT,T.FPDEPTNAME,T.FPCUST,T.FPCUSTNAME,T.CUSTDEPT,T.CUSTDEPTNAME,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,-0.5*NTAXMNY AS NMNY
						FROM (
							SELECT B.AutoID AS AutoID ,@IYEAR AS IYEAR,@I AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,
								D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
								CASE
									/*十二月收入，11月26日到12月31日*/
									WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 12  AND @I = 0 THEN B.INATSUM
									WHEN YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 AND @I = 0 THEN B.INATSUM
									/*一月收入，1月1日到1月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = 1 AND DAY(H.DDATE) <= 25 AND @I = 1 THEN B.INATSUM
									/*二月到十一月收入，上月26日到本月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = @I - 1 AND DAY(H.DDATE) > 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									WHEN  YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) = @I AND DAY(H.DDATE) <= 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									ELSE 0 END AS NTAXMNY
							FROM SALEBILLVOUCHS B
							LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
							LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
							LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
							LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
							WHERE  B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND ((YEAR(H.DDATE) = @IYEAR AND MONTH(H.DDATE) <= @I ) OR (YEAR(H.DDATE) = @IYEAR-1 AND  MONTH(H.DDATE) >= 11 ))
								AND H.cSTCode IN('02','03') AND b.iTaxUnitPrice >= 78
							UNION ALL
							SELECT B.AutoID AS AutoID ,@IYEAR-1 AS IYEAR,@I AS IPERIOD,H.CDEPCODE AS FPDEPT,D.CDEPNAME AS FPDEPTNAME,H.CCUSCODE AS FPCUST,CUST.CCUSNAME AS FPCUSTNAME,D1.CDEPCODE AS CUSTDEPT,D1.CDEPNAME AS CUSTDEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSDEPART ELSE '未匹配' END AS DIM_DEPT,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN D1.CDEPNAME ELSE '未匹配' END AS DIM_DEPTNAME,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN H.CCUSCODE ELSE '未匹配' END AS DIM_CUST,
								CASE WHEN H.CCUSCODE IN (SELECT DISTINCT #DIM.DIM_CUST FROM #DIM) THEN CUST.CCUSNAME ELSE '未匹配' END AS DIM_CUSTNAME,
								CASE
									/*十二月收入，11月26日到12月31日*/
									WHEN YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) = 12  AND @I = 0 THEN B.INATSUM
									WHEN YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) = 11 AND DAY(H.DDATE)>25 AND @I = 0 THEN B.INATSUM
									/*一月收入，1月1日到1月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = 1 AND DAY(H.DDATE) <= 25 AND @I = 1 THEN B.INATSUM
									/*二月到十一月收入，上月26日到本月25日*/
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = @I - 1 AND DAY(H.DDATE) > 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									WHEN  YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) = @I AND DAY(H.DDATE) <= 25 AND @I <> 1 AND @I <> 0 THEN B.INATSUM
									ELSE 0 END AS NTAXMNY
							FROM SALEBILLVOUCHS B
							LEFT JOIN SALEBILLVOUCH H ON B.SBVID = H.SBVID
							LEFT JOIN CUSTOMER CUST ON H.CCUSCODE = CUST.CCUSCODE
							LEFT JOIN DEPARTMENT D ON H.CDEPCODE = D.CDEPCODE
							LEFT JOIN DEPARTMENT D1 ON CUST.CCUSDEPART = D1.CDEPCODE
							WHERE   B.CINVCODE NOT LIKE '6%' AND B.CINVCODE NOT LIKE '8%' AND ((YEAR(H.DDATE) = @IYEAR-1 AND MONTH(H.DDATE) <= @I ) OR (YEAR(H.DDATE) = @IYEAR-2 AND  MONTH(H.DDATE) >= 11 ))
								AND H.cSTCode IN('02','03') AND b.iTaxUnitPrice >= 78
						)T
					SET @I = @I + 1
					END
			END
	END/*计算折让、返利的收入明细数据结束*/

	BEGIN--********费用预处理开始********
		/*能够同时匹配部门和客户的数据,销售一公司其他办事处、销售二部、销售三部、销售四部、销售五部5个部门的销售费用，全部转为公共销售费用*/
		INSERT INTO #FR_FEEDETAIL_DC
			SELECT T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,SUM(T.FEE) AS FEE_DC
			FROM #FR_FEEDETAIL_0 AS T
			WHERE T.DIM_DEPT <> '未匹配' AND T.DIM_CUST <> '未匹配' AND T.FEE <> 0 AND T.DIM_DEPT NOT IN ('0599','6902','6903','6904','6905')
			GROUP BY T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME
			ORDER BY T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME
		/*能匹配部门不能匹配客户的数据,销售一公司其他办事处、销售二部、销售三部、销售四部、销售五部5个部门的销售费用，全部转为公共销售费用*/
		INSERT INTO #FR_FEEDETAIL_D
			SELECT T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,SUM(T.FEE) AS FEE_D
			FROM #FR_FEEDETAIL_0 AS T
			WHERE T.DIM_DEPT <> '未匹配' AND T.DIM_CUST = '未匹配' AND T.FEE <> 0 AND T.DIM_DEPT NOT IN ('0599','6902','6903','6904','6905')
			GROUP BY T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME
			ORDER BY T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME
		/*能匹配客户不能匹配部门的数据,销售一公司其他办事处、销售二部、销售三部、销售四部、销售五部5个部门的销售费用，全部转为公共销售费用*/
		INSERT INTO #FR_FEEDETAIL_C
			SELECT T.IYEAR,T.IPERIOD,T.DIM_CUST,T.DIM_CUSTNAME,SUM(T.FEE) AS FEE_C
			FROM #FR_FEEDETAIL_0 AS T
			WHERE T.DIM_DEPT = '未匹配' AND T.DIM_CUST <> '未匹配' AND T.FEE <> 0 AND T.DIM_DEPT NOT IN ('0599','6902','6903','6904','6905')
			GROUP BY T.IYEAR,T.IPERIOD,T.DIM_CUST,T.DIM_CUSTNAME
			ORDER BY T.IYEAR,T.IPERIOD,T.DIM_CUST,T.DIM_CUSTNAME
		/*部门和客户都不能匹配的数据,销售一公司其他办事处、销售二部、销售三部、销售四部、销售五部5个部门的销售费用，全部转为公共销售费用*/
		INSERT INTO #FR_FEEDETAIL_Z
			SELECT T.IYEAR,T.IPERIOD,SUM(T.FEE) AS FEE_Z
			FROM #FR_FEEDETAIL_0 AS T
			WHERE (T.DIM_DEPT = '未匹配' AND T.DIM_CUST = '未匹配' OR  T.DIM_DEPT IN ('0599','6902','6903','6904','6905')) AND T.FEE <> 0
			GROUP BY T.IYEAR,T.IPERIOD
			ORDER BY T.IYEAR,T.IPERIOD
	END--********费用预处理结束********

	BEGIN--********收入预处理开始********

		/*汇总到部门和客户的数据*/
		INSERT INTO #FR_SALE_DETAIL_DC
			SELECT T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,SUM(T.NMNY) AS NMNY_DC_M,0.0 AS NMNY_DC_Y
			FROM #FR_SALE_DETAILS AS T
			GROUP BY T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME
			ORDER BY T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME

		/*汇总到部门的数据*/
		INSERT INTO #FR_SALE_DETAIL_D
			SELECT T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,SUM(T.NMNY) AS NMNY_D_M,0.0 AS NMNY_D_Y
			FROM #FR_SALE_DETAILS AS T
			GROUP BY T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME
			ORDER BY T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME
		/*汇总到客户的数据*/
		INSERT INTO #FR_SALE_DETAIL_C
			SELECT T.IYEAR,T.IPERIOD,T.DIM_CUST,T.DIM_CUSTNAME,SUM(T.NMNY) AS NMNY_C_M,0.0 AS NMNY_C_Y
			FROM #FR_SALE_DETAILS AS T
			GROUP BY T.IYEAR,T.IPERIOD,T.DIM_CUST,T.DIM_CUSTNAME
			ORDER BY T.IYEAR,T.IPERIOD,T.DIM_CUST,T.DIM_CUSTNAME
		/*总收入的数据*/
		INSERT INTO #FR_SALE_DETAIL_Z
			SELECT T.IYEAR,T.IPERIOD,SUM(T.NMNY) AS NMNY_Z_M,0.0AS NMNY_Z_Y
			FROM #FR_SALE_DETAILS AS T
			GROUP BY T.IYEAR,T.IPERIOD
			ORDER BY T.IYEAR,T.IPERIOD
		/*更新收入的年度数据*/
		SET @NSTEP = 0
		WHILE(@NSTEP<=@IPERIOD)
		BEGIN
			/*汇总到部门客户的年度收入*/
			UPDATE #FR_SALE_DETAIL_DC
			SET NMNY_DC_Y = A.NMNY_Y
			FROM (SELECT T.IYEAR,T.DIM_DEPT,T.DIM_CUST,SUM(T.NMNY_DC_M) AS NMNY_Y
				FROM #FR_SALE_DETAIL_DC AS T
				WHERE T.IPERIOD <= @NSTEP
				GROUP BY T.IYEAR,T.DIM_DEPT,T.DIM_CUST
				 ) AS A,#FR_SALE_DETAIL_DC
			 WHERE A.IYEAR = #FR_SALE_DETAIL_DC.IYEAR AND A.DIM_DEPT = #FR_SALE_DETAIL_DC.DIM_DEPT AND A.DIM_CUST = #FR_SALE_DETAIL_DC.DIM_CUST AND #FR_SALE_DETAIL_DC.IPERIOD = @NSTEP

			 /*汇总到部门的年度收入*/
			UPDATE #FR_SALE_DETAIL_D
			SET NMNY_D_Y = A.NMNY_Y
			FROM (SELECT T.IYEAR,T.DIM_DEPT,SUM(T.NMNY_D_M) AS NMNY_Y
				FROM #FR_SALE_DETAIL_D AS T
				WHERE T.IPERIOD <= @NSTEP
				GROUP BY T.IYEAR,T.DIM_DEPT
				 ) AS A,#FR_SALE_DETAIL_D
			 WHERE A.IYEAR = #FR_SALE_DETAIL_D.IYEAR AND A.DIM_DEPT = #FR_SALE_DETAIL_D.DIM_DEPT AND #FR_SALE_DETAIL_D.IPERIOD = @NSTEP

			 /*汇总到客户的年度收入*/
			UPDATE #FR_SALE_DETAIL_C
			SET NMNY_C_Y = A.NMNY_Y
			FROM (SELECT T.IYEAR,T.DIM_CUST,SUM(T.NMNY_C_M) AS NMNY_Y
				FROM #FR_SALE_DETAIL_C AS T
				WHERE T.IPERIOD <= @NSTEP
				GROUP BY T.IYEAR,T.DIM_CUST
				 ) AS A,#FR_SALE_DETAIL_C
			 WHERE A.IYEAR = #FR_SALE_DETAIL_C.IYEAR AND A.DIM_CUST = #FR_SALE_DETAIL_C.DIM_CUST AND #FR_SALE_DETAIL_C.IPERIOD = @NSTEP

			/*汇总的年度收入*/
			UPDATE #FR_SALE_DETAIL_Z
			SET NMNY_Z_Y = A.NMNY_Y
			FROM (SELECT T.IYEAR,SUM(T.NMNY_Z_M) AS NMNY_Y
				FROM #FR_SALE_DETAIL_Z AS T
				WHERE T.IPERIOD <= @NSTEP
				GROUP BY T.IYEAR
				 ) AS A,#FR_SALE_DETAIL_Z
			 WHERE A.IYEAR = #FR_SALE_DETAIL_Z.IYEAR AND #FR_SALE_DETAIL_Z.IPERIOD = @NSTEP


			SET @NSTEP = @NSTEP + 1
		END
	END--********收入预处理结束********

	BEGIN/*搭建分析表框架，把维度表写入 #FR_FEEDETAIL_1 */
		/*IYEAR INT ,IPERIOD INT ,DIM_DEPT VARCHAR(200) ,DIM_DEPTNAME VARCHAR(200),DIM_CUST VARCHAR(100) ,DIM_CUSTNAME VARCHAR(100) ,FEE_DC DECIMAL(20,2),FEE_D DECIMAL(20,2),FEE_C DECIMAL(20,2),FEE_Z DECIMAL(20,2),NMNY_DC_M DECIMAL(20,2),NMNY_D_M DECIMAL(20,2),NMNY_C_M DECIMAL(20,2),NMNY_Z_M DECIMAL(20,2),NMNY_DC_Y DECIMAL(20,2),NMNY_D_Y DECIMAL(20,2),NMNY_C_Y DECIMAL(20,2),NMNY_Z_Y DECIMAL(20,2),NCUSTCOUNT INT,FEE_D_FT DECIMAL(20,2) ,FEE_C_FT DECIMAL(20,2) ,FEE_Z_FT DECIMAL(20,2) */
		INSERT INTO #FR_FEEDETAIL_1
			SELECT #DIM.IYEAR,#DIM.IPERIOD,#DIM.DIM_DEPT,#DIM.DIM_DEPTNAME,#DIM.DIM_CUST,#DIM.DIM_CUSTNAME,0.00 AS FEE_DC,0.00 AS FEE_D ,0.00 AS FEE_C ,0.00 AS FEE_Z ,0.00 AS NMNY_DC_M ,0.00 AS NMNY_D_M ,0.00 AS NMNY_C_M,0.00 AS NMNY_Z_M ,0.00 AS NMNY_DC_Y ,0.00 AS NMNY_D_Y,0.00 AS NMNY_C_Y ,0.00 AS NMNY_Z_Y ,0 AS NCUSTCOUNT,0.00 AS FEE_D_FT,0.00 AS FEE_C_FT,0.00 AS FEE_Z_FT
			FROM #DIM
	END
	BEGIN--********费用收入数据写入开始********
		/*更新月度数据_部门客户都匹配的数据*/
			--费用数据
			UPDATE #FR_FEEDETAIL_1
			SET FEE_DC = A.FEE_DC
			FROM #FR_FEEDETAIL_DC AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT AND A.DIM_CUST = #FR_FEEDETAIL_1.DIM_CUST
			--收入数据
			UPDATE #FR_FEEDETAIL_1
			SET NMNY_DC_M = A.NMNY_DC_M
			FROM #FR_SALE_DETAIL_DC AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT AND A.DIM_CUST = #FR_FEEDETAIL_1.DIM_CUST
		/*更新月度数据_部门匹配客户不匹配的数据*/
			--费用数据
			UPDATE #FR_FEEDETAIL_1
			SET FEE_D = A.FEE_D
			FROM #FR_FEEDETAIL_D AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT
		/*更新月度数据_部门不匹配客户匹配的数据*/
			--费用数据
			UPDATE #FR_FEEDETAIL_1
			SET FEE_C = A.FEE_C
			FROM #FR_FEEDETAIL_C AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD  AND A.DIM_CUST = #FR_FEEDETAIL_1.DIM_CUST
		/*更新月度数据_部门客户都不匹配的数据*/
			--费用数据
			UPDATE #FR_FEEDETAIL_1
			SET FEE_Z = A.FEE_Z
			FROM #FR_FEEDETAIL_Z AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD
		/*更新部门收入汇总*/
			--月度部门汇总
			UPDATE #FR_FEEDETAIL_1
			SET NMNY_D_M = A.NMNY_D_M
			FROM #FR_SALE_DETAIL_D AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT
			--月度客户汇总
			UPDATE #FR_FEEDETAIL_1
			SET NMNY_C_M = A.NMNY_C_M
			FROM #FR_SALE_DETAIL_C AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_CUST = #FR_FEEDETAIL_1.DIM_CUST
			--月度总收入
			UPDATE #FR_FEEDETAIL_1
			SET NMNY_Z_M = A.NMNY_Z_M
			FROM #FR_SALE_DETAIL_Z AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD

			--
			--年度部门客户汇总
			UPDATE #FR_FEEDETAIL_1
			SET NMNY_DC_Y = A.NMNY_DC_Y
			FROM #FR_SALE_DETAIL_DC AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT AND A.DIM_CUST = #FR_FEEDETAIL_1.DIM_CUST
			--年度部门汇总
			UPDATE #FR_FEEDETAIL_1
			SET NMNY_D_Y = A.NMNY_D_Y
			FROM #FR_SALE_DETAIL_D AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT
			--年度客户汇总
			UPDATE #FR_FEEDETAIL_1
			SET NMNY_C_Y = A.NMNY_C_Y
			FROM #FR_SALE_DETAIL_C AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_CUST = #FR_FEEDETAIL_1.DIM_CUST
			--年度总收入
			UPDATE #FR_FEEDETAIL_1
			SET NMNY_Z_Y = A.NMNY_Z_Y
			FROM #FR_SALE_DETAIL_Z AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD
			--客户数
			UPDATE #FR_FEEDETAIL_1
			SET NCUSTCOUNT = A.NCUSTCOUNT
			FROM (SELECT T.IYEAR,T.IPERIOD,T.DIM_DEPT,COUNT(1) AS NCUSTCOUNT
				FROM #FR_FEEDETAIL_1 AS T
				GROUP BY T.IYEAR,T.IPERIOD,T.DIM_DEPT
				) AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT
	END--********费用收入数据写入结束********
	BEGIN -- 分配费用开始/*以下，分配部门费用*/
		UPDATE #FR_FEEDETAIL_1
			SET FEE_D_FT = A.FEE_D_FT
			FROM (SELECT  T1.IYEAR,T1.IPERIOD,T1.DIM_DEPT,T1.DIM_CUST,
						CASE WHEN  T1.NMNY_D_M <> 0 THEN ROUND(T1.FEE_D*T1.NMNY_DC_M/T1.NMNY_D_M,2)
						WHEN T1.NMNY_D_M = 0 AND T1.NMNY_D_Y <> 0 THEN ROUND(T1.FEE_D*T1.NMNY_DC_Y/T1.NMNY_D_Y,2)
						WHEN T1.NMNY_D_M = 0 AND T1.NMNY_D_Y = 0 THEN ROUND(T1.FEE_D/T1.NCUSTCOUNT,2)
						ELSE 0 END AS FEE_D_FT
				FROM #FR_FEEDETAIL_1 T1
				WHERE ISNULL(T1.FEE_D,0) <> 0 ) AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT AND A.DIM_CUST = #FR_FEEDETAIL_1.DIM_CUST


		/*以下，分配公共费用*/
		UPDATE #FR_FEEDETAIL_1
			SET FEE_Z_FT = A.FEE_Z_FT
			FROM (SELECT  T1.IYEAR,T1.IPERIOD,T1.DIM_DEPT,T1.DIM_CUST,
						CASE WHEN  T1.NMNY_Z_M <> 0 THEN ROUND(T1.FEE_Z*T1.NMNY_DC_M/T1.NMNY_Z_M,2) ELSE 0 END AS FEE_Z_FT
				FROM #FR_FEEDETAIL_1 T1 /*
				WHERE ISNULL(T1.FEE_D,0) <> 0 这个条件应该去掉*/ ) AS A,#FR_FEEDETAIL_1
			WHERE A.IYEAR = #FR_FEEDETAIL_1.IYEAR AND A.IPERIOD = #FR_FEEDETAIL_1.IPERIOD AND A.DIM_DEPT = #FR_FEEDETAIL_1.DIM_DEPT AND A.DIM_CUST = #FR_FEEDETAIL_1.DIM_CUST
	END -- 分配费用结束
	BEGIN-- 查询结果开始
		SELECT
			T.IYEAR,T.IPERIOD,T.DIM_DEPT,T.DIM_DEPTNAME,T.DIM_CUST,T.DIM_CUSTNAME,T.FEE_DC,T.FEE_D,T.FEE_Z,T.NMNY_DC_M,T.NMNY_D_M,T.NMNY_Z_M,T.NMNY_DC_Y,T.NMNY_D_Y,T.NMNY_Z_Y ,T.NCUSTCOUNT ,T.FEE_D_FT,T.FEE_Z_FT,
			T1.FEE_DC AS FEE_DC_0,T1.FEE_D AS FEE_D_0,T1.FEE_Z AS FEE_Z_0,T1.NMNY_DC_M AS NMNY_DC_M_0,T1.NMNY_D_M AS NMNY_D_M_0,T1.NMNY_Z_M AS NMNY_Z_M_0,T1.NMNY_DC_Y AS NMNY_DC_Y_0,T1.NMNY_D_Y AS NMNY_D_Y_0,T1.NMNY_Z_Y AS NMNY_Z_Y_0 ,T1.NCUSTCOUNT AS NCUSTCOUNT_0 ,T1.FEE_D_FT AS FEE_D_FT_0,T1.FEE_Z_FT AS FEE_Z_FT_0,
			(T.FEE_DC+T.FEE_D_FT+T.FEE_Z_FT) AS F_F_M,
			(SELECT SUM(X1.FEE_DC+X1.FEE_D_FT+X1.FEE_Z_FT) FROM #FR_FEEDETAIL_1 AS X1 WHERE X1.IYEAR = @IYEAR AND X1.IPERIOD <= @IPERIOD AND X1.DIM_DEPT = T.DIM_DEPT AND X1.DIM_CUST = T.DIM_CUST) AS F_F_Y,
			(T1.FEE_DC+T1.FEE_D_FT+T1.FEE_Z_FT) AS F_F_M_0,
			(SELECT SUM(X2.FEE_DC+X2.FEE_D_FT+X2.FEE_Z_FT) FROM #FR_FEEDETAIL_1 AS X2 WHERE X2.IYEAR = @IYEAR-1 AND X2.IPERIOD <= @IPERIOD AND X2.DIM_DEPT = T.DIM_DEPT AND X2.DIM_CUST = T.DIM_CUST) AS F_F_Y_0,
			T2.salefee_m AS salefee_m,T3.salefee_m AS salefee_m_0,T2.salefee_y AS salefee_y,T3.salefee_y AS salefee_y_0
			FROM #FR_FEEDETAIL_1 T
			LEFT JOIN #FR_FEEDETAIL_1 T1 ON T.IYEAR-1 = T1.IYEAR AND T.IPERIOD = T1.IPERIOD AND T.DIM_DEPT = T1.DIM_DEPT AND T.DIM_CUST = T1.DIM_CUST
			LEFT JOIN (
				--今年折半费用
					SELECT
						t.DIM_DEPT,t.DIM_DEPTNAME,t.DIM_CUST,t.DIM_CUSTNAME,SUM(-1*t.NMNY) as salefee_y,sum(case when t.IPERIOD = @IPERIOD then -1*t.NMNY else 0 END) as salefee_m
						FROM  #FR_SALE_DETAILS as t
						WHERE t.IFLAG = 1 AND t.IYEAR = @IYEAR and t.NMNY <> 0
						group by t.DIM_DEPT,t.DIM_DEPTNAME,t.DIM_CUST,t.DIM_CUSTNAME
			) T2 ON  T.DIM_DEPT = T2.DIM_DEPT AND T.DIM_CUST = T2.DIM_CUST
			LEFT JOIN (
				--去年折半费用
					SELECT
						t.DIM_DEPT,t.DIM_DEPTNAME,t.DIM_CUST,t.DIM_CUSTNAME,SUM(-1*t.NMNY) as salefee_y,sum(case when t.IPERIOD = @IPERIOD then -1*t.NMNY else 0 END) as salefee_m
						FROM  #FR_SALE_DETAILS as t
						WHERE t.IFLAG = 1 AND t.IYEAR = @IYEAR-1 and t.NMNY <> 0
						group by t.DIM_DEPT,t.DIM_DEPTNAME,t.DIM_CUST,t.DIM_CUSTNAME
			) T3 ON  T.DIM_DEPT = T3.DIM_DEPT AND T.DIM_CUST = T3.DIM_CUST
			WHERE  T.IYEAR = @IYEAR AND T.IPERIOD = @IPERIOD
			ORDER BY T.DIM_DEPT

		SELECT t.DIM_DEPT,t.DIM_DEPTNAME,t.DIM_CUST,t.DIM_CUSTNAME,SUM(-1*t.NMNY) as salefee
			FROM  #FR_SALE_DETAILS as t
			WHERE t.IFLAG = 1 AND t.IYEAR = @IYEAR AND t.IPERIOD = @IPERIOD and t.NMNY <> 0
			group by t.DIM_DEPT,t.DIM_DEPTNAME,t.DIM_CUST,t.DIM_CUSTNAME
			
	END --查询结果结束

END
